name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev
      - name: Install Cargo dependencies
        run: cargo install cargo-deb
      - name: Create package
        run: cargo deb --verbose
      - name: Archive generated package
        uses: actions/upload-artifact@v2
        with:
          name: debian_packages.zip
          path: target/debian/*.deb
